<?php
// module/Product/view/product/product/edit.phtml:
 
$title       = 'Редактирование поставщика "' . $productName . '"';
$parent_page = 'Поставщики';
$this->headTitle($title);
?>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Администрирование</li>
    <li class="breadcrumb-item" aria-current="page"><a href="/product"><?= $this->escapeHtml($parent_page) ?></a></li>
    <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml('Редактирование поставщика') ?></li>
  </ol>
</nav>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'product',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('product_id'));?>
<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('product_name')); ?>
    </div>
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('email')); ?>
    </div>
</div>
<div class="mb-3">
<?php echo $this->formRow($form->get('comment')); ?>
</div>

<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('margin_fix')); ?>
    </div>
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('margin_percent')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('product_delivery_time')); ?>
    </div>
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('default_contragent_id')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('status')); ?>
    </div>
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('product_update_interval')); ?>
    </div>
</div>
<div class="mb-4">
<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>

<hr>

<h1><?= $this->escapeHtml('Склады поставщика "') . $productName . '"'?></h1>

<div class="sp"></div>

<a href="<?= $this->url('product-stock', ['action' => 'add', 'product_id' => $this->id]) ?>">
    <button type="button" class="btn btn-primary btn-sm">Добавить склад</button>
</a>

<div class="sp"></div>
<div class="sp"></div>
<?php if (count($productStocks)) {?>
<table id="product_stock_list" class="table table-hover table-striped">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Название</th>
            <th>Срок доставки</th>
            <th>Наценка (ф.)</th>
            <th>Наценка (%)</th>
            <th>Статус</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($productStocks as $productStock) : ?>
        <tr>
            <td></td>
            <td><?= $productStock->product_stock_id ?></td>
            <td>
                <a href="<?= $this->url('product-stock', ['action' => 'edit', 'product_id' => $id, 'id' => $productStock->product_stock_id]) ?>">
                <?= $this->escapeHtml($productStock->stock_name) ?>
                </a>
            </td>
            <td><?= $productStock->delivery_time ?></td>
            <td><?= $productStock->margin_fix ?></td>
            <td><?= $productStock->margin_percent ?></td>
            <td><?= ($productStock->status > -1) ? $statusValue[$productStock->status] : '' ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php } else { ?>
<div class="alert alert-primary" role="alert">
  Складов у поставщика нет.
</div>
<?php } ?>
