<?php
// module/SupplierStock/view/supplier-stock/supplier-stock/edit.phtml:
 
$title = 'Добавление склада';
$this->headTitle($title);
?>


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Администрирование</li>
    <li class="breadcrumb-item" aria-current="page"><a href="/supplier"><?= $this->escapeHtml('Поставщики') ?></a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="/supplier/edit/<?= $this->supplier_id ?>"><?= $this->escapeHtml($this->supplier_name) ?></a></li>
    <li class="breadcrumb-item active" aria-current="page"><?= $this->escapeHtml($title) ?></li>
  </ol>
</nav>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'supplier-stock',
    array(
        'action'      => 'add',
        'supplier_id' => $this->supplier_id,
    )
));
$form->prepare();
 
echo $this->form()->openTag($form);?>
<input name="supplier_id" type="hidden" value="<?= $this->supplier_id ?>">
<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('stock_name')); ?>
    </div>
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('delivery_time')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('margin_fix')); ?>
    </div>
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('margin_percent')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6 mb-3">
<?php echo $this->formRow($form->get('status')); ?>
    </div>
</div>
<div class="mb-4">
<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>